---
abstract: Module::Starter plugin which creates debian package config files
author:
  - 'Bradley Dean <bjdean@bjdean.id.au>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Module-Starter-Plugin-DebPackage
no_index:
  directory:
    - inc
    - t
requires:
  Module::Starter::Simple: 0
  version: 0
version: !!perl/hash:version
  original: 0.0.4
  qv: 1
  version:
    - 0
    - 0
    - 4
